name: daily_you
description: Every day is worth remembering...
publish_to: 'none'
version: 1.8.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: 
  path_provider: 
  sqflite_common_ffi:
  sqlite3_flutter_libs:
  flutter_markdown: ^0.6.15
  file_picker: ^6.1.1
  provider: ^6.0.5
  path: ^1.9.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.0
  easy_debounce: ^2.0.3
  table_calendar: ^3.0.9
  system_theme: ^2.3.1
  url_launcher: ^6.1.12
  icons_launcher: ^2.1.3
  photo_view: ^0.14.0
  media_scanner: ^2.1.0
  flutter_local_notifications: ^16.3.0
  android_alarm_manager_plus: ^3.0.2
  flutter_colorpicker: ^1.0.3
  share_extend: ^2.0.0
  shared_storage:
    git:
      url: https://github.com/Demizo/shared-storage
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/logo_rectangle.png"
      adaptive_background_image: "assets/logo_background.png"
      adaptive_foreground_image: "assets/logo_foreground.png"
      adaptive_round_image: "assets/logo.png"
      adaptive_monochrome_image: "assets/logo_monochrome.png"
    ios:
      enable: false
      image_path: "assets/logo_rectangle.png"
    macos:
      enable: false
      image_path: "assets/logo_border.png"
    windows:
      enable: false
      image_path: "assets/logo.png"
    linux:
      enable: true
      image_path: "assets/logo.png"
