name: daily_you
description: Every day is worth remembering...
publish_to: 'none'
version: 2.7.1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: 
  path_provider: 
  sqflite_common_ffi:
  sqlite3_flutter_libs:
  flutter_markdown: ^0.7.5
  file_picker: ^8.1.7
  provider: ^6.0.5
  path: ^1.9.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.0
  easy_debounce: ^2.0.3
  table_calendar: ^3.1.3
  system_theme: ^3.1.2
  url_launcher: ^6.1.12
  icons_launcher: ^3.0.0
  flutter_local_notifications: ^18.0.1
  android_alarm_manager_plus: ^4.0.5
  flutter_colorpicker: ^1.0.3
  shared_storage:
    git:
      url: https://github.com/Demizo/shared-storage
      ref: release
  media_scanner:
    git:
      url: https://github.com/mbfakourii/media_scanner.git
      ref: support_gradle_8
  device_info_plus: ^11.2.0
  fl_chart: ^0.66.2
  markdown_toolbar: ^0.5.0
  markdown_widget: ^2.3.2+3

  intl: ^0.19.0
  share_plus: ^10.1.3
  cached_memory_image: ^1.5.0
  schedulers: ^1.0.1
  time_range_picker: ^2.3.0
  package_info_plus: ^8.1.3
  shared_preferences: ^2.5.2
  saf_util: ^0.6.2
  saf_stream: ^0.11.1
  archive: ^4.0.5
  mime: ^2.0.0
  scroll_to_hide: ^2.2.0
  extended_image: ^9.1.0
dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/logo_rectangle.png"
      adaptive_background_image: "assets/logo_background.png"
      adaptive_foreground_image: "assets/logo_foreground.png"
      adaptive_round_image: "assets/logo.png"
      adaptive_monochrome_image: "assets/logo_monochrome.png"
    ios:
      enable: false
      image_path: "assets/logo_rectangle.png"
    macos:
      enable: false
      image_path: "assets/logo_border.png"
    windows:
      enable: false
      image_path: "assets/logo.png"
    linux:
      enable: true
      image_path: "assets/logo.png"
