name: daily_you
description: Every day is worth remembering...
publish_to: 'none'
version: 2.13.1+2013001

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: 
  path_provider: 
  sqflite_common_ffi:
  sqlite3_flutter_libs:
  file_picker: ^10.1.9
  provider: ^6.0.5
  path: ^1.9.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.0
  easy_debounce: ^2.0.3
  table_calendar: ^3.1.3
  system_theme: ^3.1.2
  url_launcher: ^6.1.12
  icons_launcher: ^3.0.0
  flutter_local_notifications: ^19.2.1
  android_alarm_manager_plus: ^4.0.5
  flutter_colorpicker: ^1.0.3
  shared_storage:
    git:
      url: https://github.com/Demizo/shared-storage
      ref: release
  device_info_plus: ^11.2.0
  fl_chart: ^0.66.2
  markdown_widget: ^2.3.2+3

  intl: ^0.20.0
  share_plus: ^10.1.3
  time_range_picker: ^2.3.0
  package_info_plus: ^8.1.3
  shared_preferences: ^2.5.2
  saf_util: ^0.10.0
  saf_stream: ^0.11.1
  archive: ^4.0.7
  mime: ^2.0.0
  extended_image: ^9.1.0
  app_settings: ^6.1.1
  image: ^4.5.4
  flutter_cache_manager: ^3.4.1
  statsfl: ^2.3.0
  pool: ^1.5.1
  flutter_image_compress: ^2.4.0
  html2md: ^1.3.2
  media_scanner: ^2.2.0
  local_auth: ^2.3.0
  crypto: ^3.0.6
  flutter_svg: ^2.2.0
dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/calendar_event.svg
    - assets/icons/calendar_latest.svg

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/logo_rectangle.png"
      notification_image: "assets/logo_notification.png"
      adaptive_background_image: "assets/logo_background.png"
      adaptive_foreground_image: "assets/logo_foreground.png"
      adaptive_round_image: "assets/logo.png"
      adaptive_monochrome_image: "assets/logo_monochrome.png"
    ios:
      enable: false
      image_path: "assets/logo_rectangle.png"
    macos:
      enable: false
      image_path: "assets/logo_border.png"
    windows:
      enable: false
      image_path: "assets/logo.png"
    linux:
      enable: true
      image_path: "assets/logo.png"
