import 'package:daily_you/l10n/generated/app_localizations.dart';
import 'package:flutter/material.dart';

enum TagIconGroupId {
  moodPeople,
  habitsGoals,
  activities,
  health,
  workFinance,
  natureWeather,
  foodDrink,
  home,
  hobbies,
  travel,
  symbols,
}

class TagIconGroup {
  final TagIconGroupId id;
  final List<String> keys;

  const TagIconGroup({required this.id, required this.keys});
}

String tagIconGroupLabel(AppLocalizations l10n, TagIconGroupId id) =>
    switch (id) {
      TagIconGroupId.moodPeople => l10n.iconGroupMoodPeople,
      TagIconGroupId.habitsGoals => l10n.iconGroupHabitsGoals,
      TagIconGroupId.activities => l10n.iconGroupActivities,
      TagIconGroupId.health => l10n.iconGroupHealth,
      TagIconGroupId.workFinance => l10n.iconGroupWorkFinance,
      TagIconGroupId.natureWeather => l10n.iconGroupNatureWeather,
      TagIconGroupId.foodDrink => l10n.iconGroupFoodDrink,
      TagIconGroupId.home => l10n.iconGroupHome,
      TagIconGroupId.hobbies => l10n.iconGroupHobbies,
      TagIconGroupId.travel => l10n.iconGroupTravel,
      TagIconGroupId.symbols => l10n.iconGroupSymbols,
    };

const Map<String, IconData> tagIconRegistry = {
  'mood': Icons.mood_rounded,
  'sentiment_very_satisfied': Icons.sentiment_very_satisfied_rounded,
  'sentiment_satisfied': Icons.sentiment_satisfied_rounded,
  'sentiment_neutral': Icons.sentiment_neutral_rounded,
  'sentiment_dissatisfied': Icons.sentiment_dissatisfied_rounded,
  'sentiment_very_dissatisfied': Icons.sentiment_very_dissatisfied_rounded,
  'mood_bad': Icons.mood_bad_rounded,
  'emoji_emotions': Icons.emoji_emotions_rounded,
  'sick': Icons.sick_rounded,
  'favorite': Icons.favorite_rounded,
  'face': Icons.face_rounded,
  'groups': Icons.groups_rounded,
  'person': Icons.person_rounded,
  'family_restroom': Icons.family_restroom_rounded,
  'child_care': Icons.child_care_rounded,
  'child_friendly': Icons.child_friendly_rounded,
  'elderly': Icons.elderly_rounded,
  'pregnant_woman': Icons.pregnant_woman_rounded,
  'pets': Icons.pets_rounded,
  'celebration': Icons.celebration_rounded,
  'handshake': Icons.handshake_rounded,

  'task_alt': Icons.task_alt_rounded,
  'check_circle': Icons.check_circle_rounded,
  'repeat': Icons.repeat_rounded,
  'whatshot': Icons.whatshot_rounded,
  'military_tech': Icons.military_tech_rounded,
  'verified': Icons.verified_rounded,
  'block': Icons.block_rounded,
  'schedule': Icons.schedule_rounded,
  'hourglass_bottom': Icons.hourglass_bottom_rounded,

  'directions_run': Icons.directions_run_rounded,
  'directions_walk': Icons.directions_walk_rounded,
  'directions_bike': Icons.directions_bike_rounded,
  'fitness_center': Icons.fitness_center_rounded,
  'sports_soccer': Icons.sports_soccer_rounded,
  'sports_basketball': Icons.sports_basketball_rounded,
  'sports_tennis': Icons.sports_tennis_rounded,
  'sports_volleyball': Icons.sports_volleyball_rounded,
  'sports_football': Icons.sports_football_rounded,
  'sports_rugby': Icons.sports_rugby_rounded,
  'sports_hockey': Icons.sports_hockey_rounded,
  'sports_martial_arts': Icons.sports_martial_arts_rounded,
  'sports_esports': Icons.sports_esports_rounded,
  'hiking': Icons.hiking_rounded,
  'pool': Icons.pool_rounded,
  'self_improvement': Icons.self_improvement_rounded,
  'golf_course': Icons.golf_course_rounded,
  'rowing': Icons.rowing_rounded,
  'sailing': Icons.sailing_rounded,
  'kayaking': Icons.kayaking_rounded,
  'surfing': Icons.surfing_rounded,
  'skateboarding': Icons.skateboarding_rounded,
  'snowboarding': Icons.snowboarding_rounded,
  'downhill_skiing': Icons.downhill_skiing_rounded,
  'nordic_walking': Icons.nordic_walking_rounded,
  'scuba_diving': Icons.scuba_diving_rounded,
  'snowshoeing': Icons.snowshoeing_rounded,

  'favorite_border': Icons.favorite_border_rounded,
  'local_hospital': Icons.local_hospital_rounded,
  'medication': Icons.medication_rounded,
  'medication_liquid': Icons.medication_liquid_rounded,
  'monitor_heart': Icons.monitor_heart_rounded,
  'monitor_weight': Icons.monitor_weight_rounded,
  'bloodtype': Icons.bloodtype_rounded,
  'vaccines': Icons.vaccines_rounded,
  'bedtime': Icons.bedtime_rounded,
  'spa': Icons.spa_rounded,
  'bathtub': Icons.bathtub_rounded,
  'soap': Icons.soap_rounded,
  'shower': Icons.shower_rounded,
  'water_drop': Icons.water_drop_rounded,
  'smoking_rooms': Icons.smoking_rooms_rounded,
  'smoke_free': Icons.smoke_free_rounded,
  'no_drinks': Icons.no_drinks_rounded,
  'psychology': Icons.psychology_rounded,
  'healing': Icons.healing_rounded,
  'masks': Icons.masks_rounded,
  'battery_charging_full': Icons.battery_charging_full_rounded,
  'battery_alert': Icons.battery_alert_rounded,

  'work': Icons.work_rounded,
  'business_center': Icons.business_center_rounded,
  'meeting_room': Icons.meeting_room_rounded,
  'school': Icons.school_rounded,
  'menu_book': Icons.menu_book_rounded,
  'edit_note': Icons.edit_note_rounded,
  'assignment': Icons.assignment_rounded,
  'assignment_turned_in': Icons.assignment_turned_in_rounded,
  'checklist': Icons.checklist_rounded,
  'laptop_mac': Icons.laptop_mac_rounded,
  'attach_money': Icons.attach_money_rounded,
  'trending_up': Icons.trending_up_rounded,
  'savings': Icons.savings_rounded,
  'credit_card': Icons.credit_card_rounded,
  'paid': Icons.paid_rounded,
  'shopping_cart': Icons.shopping_cart_rounded,
  'shopping_bag': Icons.shopping_bag_rounded,
  'receipt_long': Icons.receipt_long_rounded,
  'account_balance': Icons.account_balance_rounded,

  'wb_sunny': Icons.wb_sunny_rounded,
  'cloud': Icons.cloud_rounded,
  'water': Icons.water_rounded,
  'waves': Icons.waves_rounded,
  'umbrella': Icons.umbrella_rounded,
  'ac_unit': Icons.ac_unit_rounded,
  'cyclone': Icons.cyclone_rounded,
  'air': Icons.air_rounded,
  'park': Icons.park_rounded,
  'forest': Icons.forest_rounded,
  'grass': Icons.grass_rounded,
  'landscape': Icons.landscape_rounded,
  'local_florist': Icons.local_florist_rounded,
  'eco': Icons.eco_rounded,
  'terrain': Icons.terrain_rounded,
  'nightlight': Icons.nightlight_rounded,
  'wb_twilight': Icons.wb_twilight_rounded,
  'thunderstorm': Icons.thunderstorm_rounded,

  'restaurant_menu': Icons.restaurant_menu_rounded,
  'local_dining': Icons.local_dining_rounded,
  'local_pizza': Icons.local_pizza_rounded,
  'ramen_dining': Icons.ramen_dining_rounded,
  'fastfood': Icons.fastfood_rounded,
  'no_food': Icons.no_food_rounded,
  'cake': Icons.cake_rounded,
  'icecream': Icons.icecream_rounded,
  'local_bar': Icons.local_bar_rounded,
  'wine_bar': Icons.wine_bar_rounded,
  'sports_bar': Icons.sports_bar_rounded,
  'coffee': Icons.coffee_rounded,
  'lunch_dining': Icons.lunch_dining_rounded,
  'bakery_dining': Icons.bakery_dining_rounded,
  'set_meal': Icons.set_meal_rounded,
  'liquor': Icons.liquor_rounded,
  'restaurant': Icons.restaurant_rounded,
  'local_cafe': Icons.local_cafe_rounded,
  'local_drink': Icons.local_drink_rounded,

  'home': Icons.home_rounded,
  'bed': Icons.bed_rounded,
  'chair': Icons.chair_rounded,
  'checkroom': Icons.checkroom_rounded,
  'cleaning_services': Icons.cleaning_services_rounded,
  'local_laundry_service': Icons.local_laundry_service_rounded,
  'iron': Icons.iron_rounded,
  'build': Icons.build_rounded,
  'handyman': Icons.handyman_rounded,
  'construction': Icons.construction_rounded,
  'yard': Icons.yard_rounded,

  'palette': Icons.palette_rounded,
  'brush': Icons.brush_rounded,
  'piano': Icons.piano_rounded,
  'theater_comedy': Icons.theater_comedy_rounded,
  'theaters': Icons.theaters_rounded,
  'queue_music': Icons.queue_music_rounded,
  'camera_alt': Icons.camera_alt_rounded,
  'music_note': Icons.music_note_rounded,
  'movie': Icons.movie_rounded,
  'videogame_asset': Icons.videogame_asset_rounded,
  'book': Icons.book_rounded,
  'headphones': Icons.headphones_rounded,
  'weekend': Icons.weekend_rounded,

  'flight': Icons.flight_rounded,
  'directions_car': Icons.directions_car_rounded,
  'directions_boat': Icons.directions_boat_rounded,
  'directions_subway': Icons.directions_subway_rounded,
  'local_taxi': Icons.local_taxi_rounded,
  'electric_scooter': Icons.electric_scooter_rounded,
  'train': Icons.train_rounded,
  'directions_bus': Icons.directions_bus_rounded,
  'luggage': Icons.luggage_rounded,
  'map': Icons.map_rounded,
  'beach_access': Icons.beach_access_rounded,
  'hotel': Icons.hotel_rounded,
  'public': Icons.public_rounded,

  'star': Icons.star_rounded,
  'bolt': Icons.bolt_rounded,
  'wb_incandescent': Icons.wb_incandescent_rounded,
  'flag': Icons.flag_rounded,
  'alarm': Icons.alarm_rounded,
  'event': Icons.event_rounded,
  'today': Icons.today_rounded,
  'timeline': Icons.timeline_rounded,
  'label': Icons.label_rounded,
  'lightbulb': Icons.lightbulb_rounded,
  'emoji_events': Icons.emoji_events_rounded,
  'volunteer_activism': Icons.volunteer_activism_rounded,
  'church': Icons.church_rounded,
  'phone_iphone': Icons.phone_iphone_rounded,
  'chat': Icons.chat_rounded,
  'email': Icons.email_rounded,
  'folder': Icons.folder_rounded,
  'category': Icons.category_rounded,
  'push_pin': Icons.push_pin_rounded,
};

const List<TagIconGroup> tagIconGroups = [
  TagIconGroup(id: TagIconGroupId.moodPeople, keys: [
    'mood',
    'sentiment_very_satisfied',
    'sentiment_satisfied',
    'sentiment_neutral',
    'sentiment_dissatisfied',
    'sentiment_very_dissatisfied',
    'mood_bad',
    'emoji_emotions',
    'sick',
    'favorite',
    'face',
    'groups',
    'person',
    'family_restroom',
    'child_care',
    'child_friendly',
    'elderly',
    'pregnant_woman',
    'pets',
    'celebration',
    'handshake',
  ]),
  TagIconGroup(id: TagIconGroupId.habitsGoals, keys: [
    'task_alt',
    'check_circle',
    'repeat',
    'whatshot',
    'military_tech',
    'verified',
    'block',
    'schedule',
    'hourglass_bottom',
  ]),
  TagIconGroup(id: TagIconGroupId.activities, keys: [
    'directions_run',
    'directions_walk',
    'directions_bike',
    'fitness_center',
    'sports_soccer',
    'sports_basketball',
    'sports_tennis',
    'sports_volleyball',
    'sports_football',
    'sports_rugby',
    'sports_hockey',
    'sports_martial_arts',
    'sports_esports',
    'hiking',
    'pool',
    'self_improvement',
    'golf_course',
    'rowing',
    'sailing',
    'kayaking',
    'surfing',
    'skateboarding',
    'snowboarding',
    'downhill_skiing',
    'nordic_walking',
    'scuba_diving',
    'snowshoeing',
  ]),
  TagIconGroup(id: TagIconGroupId.health, keys: [
    'favorite_border',
    'local_hospital',
    'medication',
    'medication_liquid',
    'monitor_heart',
    'monitor_weight',
    'bloodtype',
    'vaccines',
    'bedtime',
    'spa',
    'bathtub',
    'soap',
    'shower',
    'water_drop',
    'smoking_rooms',
    'smoke_free',
    'no_drinks',
    'psychology',
    'healing',
    'masks',
    'battery_charging_full',
    'battery_alert',
  ]),
  TagIconGroup(id: TagIconGroupId.workFinance, keys: [
    'work',
    'business_center',
    'meeting_room',
    'school',
    'menu_book',
    'edit_note',
    'assignment',
    'assignment_turned_in',
    'checklist',
    'laptop_mac',
    'attach_money',
    'trending_up',
    'savings',
    'credit_card',
    'paid',
    'shopping_cart',
    'shopping_bag',
    'receipt_long',
    'account_balance',
  ]),
  TagIconGroup(id: TagIconGroupId.natureWeather, keys: [
    'wb_sunny',
    'cloud',
    'water',
    'waves',
    'umbrella',
    'ac_unit',
    'cyclone',
    'air',
    'park',
    'forest',
    'grass',
    'landscape',
    'local_florist',
    'eco',
    'terrain',
    'nightlight',
    'wb_twilight',
    'thunderstorm',
  ]),
  TagIconGroup(id: TagIconGroupId.foodDrink, keys: [
    'restaurant_menu',
    'local_dining',
    'local_pizza',
    'ramen_dining',
    'fastfood',
    'no_food',
    'cake',
    'icecream',
    'local_bar',
    'wine_bar',
    'sports_bar',
    'coffee',
    'lunch_dining',
    'bakery_dining',
    'set_meal',
    'liquor',
    'restaurant',
    'local_cafe',
    'local_drink',
  ]),
  TagIconGroup(id: TagIconGroupId.home, keys: [
    'home',
    'bed',
    'chair',
    'checkroom',
    'cleaning_services',
    'local_laundry_service',
    'iron',
    'build',
    'handyman',
    'construction',
    'yard',
  ]),
  TagIconGroup(id: TagIconGroupId.hobbies, keys: [
    'palette',
    'brush',
    'piano',
    'theater_comedy',
    'theaters',
    'queue_music',
    'camera_alt',
    'music_note',
    'movie',
    'videogame_asset',
    'book',
    'headphones',
    'weekend',
  ]),
  TagIconGroup(id: TagIconGroupId.travel, keys: [
    'flight',
    'directions_car',
    'directions_boat',
    'directions_subway',
    'local_taxi',
    'electric_scooter',
    'train',
    'directions_bus',
    'luggage',
    'map',
    'beach_access',
    'hotel',
    'public',
  ]),
  TagIconGroup(id: TagIconGroupId.symbols, keys: [
    'star',
    'bolt',
    'wb_incandescent',
    'flag',
    'alarm',
    'event',
    'today',
    'timeline',
    'label',
    'lightbulb',
    'emoji_events',
    'volunteer_activism',
    'church',
    'phone_iphone',
    'chat',
    'email',
    'folder',
    'category',
    'push_pin',
  ]),
];

IconData? lookupTagIcon(String? key) =>
    key == null ? null : tagIconRegistry[key];
